### PR TITLE
Model notebook

### PR DESCRIPTION
**Pull request by manangoel99**
Implemented Model with ray for parallel processing of frames and output video with identified emotions by @manangoel99 and @riz1-ali . Updated docker settings for running server inside docker container.

Use ```docker-compose up``` to run

### CODE REVIEW

**Comment by manangoel99** [comment]
To run model with test video
```
docker-compose up
```
Open a new tab
```
docker ps
```
See container ID
```
docker exec -it <container_id> bash
cd notebooks
python model.py
```

Whoever reviews, please use this

**Comment by dvijaywargiya** [comment]
image

Getting this error on running docker-compose up

**Comment by manangoel99** [comment]
I've changed the version. Please try now. Run ```docker-compose --version``` and send output.

**Comment by dvijaywargiya** [comment]
ERROR: Couldn't find env file: /home/devesh/Devesh/3rd Year/6th Semester/Software Engineering/PROJECT/EmotionDetector/.env

Getting this now.

**Comment by manangoel99** [comment]
Pull now and run. Added the .env file. It was in .gitignore so it was ignored in the commit

**Comment by dvijaywargiya** [comment]
Works, GG

**Pull request merged**
